"""add user_id to sales

Revision ID: 6bf070b380ee
Revises: c842d36c46bf
Create Date: 2026-09-27 07:16:57.469849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf070b380ee'
down_revision: Union[str, Sequence[str], None] = 'c842d36c46bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'sales',
        sa.Column('user_id', sa.Integer(), nullable=True)
    )

    op.create_foreign_key(
        'sales_user_id_fkey',
        'sales',
        'users',
        ['user_id'],
        ['id']
    )

def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'sales',
        sa.Column('user_id', sa.Integer(), nullable=True)
    )

    op.create_foreign_key(
        'sales_user_id_fkey',
        'sales',
        'users',
        ['user_id'],
        ['id']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('drug_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key(op.f('sales_drug_id_fkey'), 'sales', 'drugs', ['drug_id'], ['id'])
    op.create_foreign_key(op.f('sales_sale_id_fkey'), 'sales', 'sales', ['sale_id'], ['id'])
    op.drop_column('sales', 'user_id')
    op.create_table('prescription_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dose_instructions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('prescription_items_prescription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prescription_items_pkey'))
    )
    op.create_index(op.f('ix_prescription_items_id'), 'prescription_items', ['id'], unique=False)
    # ### end Alembic commands ###
