"""cleanup sales structure

Revision ID: ebfb47bfba73
Revises: 6bf070b380ee
Create Date: 2026-09-27 07:57:10.419798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfb47bfba73'
down_revision: Union[str, Sequence[str], None] = '6bf070b380ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sales_drug_id_fkey'), 'sales', type_='foreignkey')
    op.drop_constraint(op.f('sales_sale_id_fkey'), 'sales', type_='foreignkey')
    op.drop_column('sales', 'quantity')
    op.drop_column('sales', 'total')
    op.drop_column('sales', 'unit_price')
    op.drop_column('sales', 'drug_id')
    op.drop_column('sales', 'sale_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('drug_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sales_sale_id_fkey'), 'sales', 'sales', ['sale_id'], ['id'])
    op.create_foreign_key(op.f('sales_drug_id_fkey'), 'sales', 'drugs', ['drug_id'], ['id'])
    # ### end Alembic commands ###
